name: video_editor
version: 2.4.0
description: |
 A flutter package for editing video with fully customizable UI.
 Supports crop, trim, rotation and cover selection.
 Video and cover exportation is handled by ffmpeg
repository: https://github.com/LeGoffMael/video_editor

environment:
  flutter: ">=3.0.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  ffmpeg_kit_flutter_full: ^6.0.3
  path: ^1.8.3
  path_provider: ^2.1.2
  transparent_image: ^2.0.1 # show fade-in placeholder in thumbnails generation
  video_player: ^2.8.3
  video_thumbnail: ^0.5.3
  helpers: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

screenshots:
  - description: 'Video editor demo'
    path: assets/demo_thumb.webp